# Generated by Django 5.0.2 on 2024-02-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
